namespace: oktoberfest

resources:
  - namespace.yaml
  - secret.yaml
  - db-pvc.yaml
  - db-deployment.yaml
  - db-service.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
